### ISSUE TITLE
Additional reference links are mangled by `changelog release`

### ISSUE THREAD

**Issue by mattwynne** [cucumber/changelog#9]
### 👓 What did you see?

e.g. https://github.com/cucumber/html-formatter/commit/b41c7785be35767c1c7f789456a47067cd6f9ef6#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

### ✅ What did you expect to see?

Manually-added reference links should be left alone when running `changelog release`

### 📦 Which tool/library version are you using?

Latest

### 🔬 How could we reproduce it?

1. add a reference link at the bottom of the document
2. run `changelog release`

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by mpkorstanje** [comment]
Not only additional reference links:

https://github.com/cucumber/polyglot-release/commit/1baab2f6fff20219f223b81e08b38efed2b8158a

**Comment by mattwynne** [comment]
OK so I think I figured out that this is a problem with the way the `-o` switch works.

If I run `changelog fmt` in `cucumber/messages` right now, I see the correct file content (well, the reference links have been inlined, but there's no crap at the bottom) *but* if I run it with `changelog fmt -o CHANGELOG.md` then there are a few lines of half-written reference links at the bottom of the file.

My guess is that the `-o` switch is overwriting the existing file's content rather than re-writing it, and leaving the characters at the end. Need to investigate.

I've also found it fails if you just try to pipe the output `changelog fmt > CHANGELOG.md` so I can maybe fix that at the same time.

**Comment by mattwynne** [comment]
Code at fault is around here: https://github.com/cucumber/changelog/blob/main/cmd/root.go#L31

Probably we need to write to a temporary file and then move that file over the top of the existing `CHANGELOG.md` when we're done.

**Comment by mpkorstanje** [comment]
You can use `O_TRUNK` to empty the file before writing new contents.

https://pkg.go.dev/os#pkg-constants

**Comment by mattwynne** [comment]
hmmm. I tried that, and it seems like what you get then is a file written with just the new title,

```
# Changelog
```

It appears to me that the input stream is not independent from the output stream, so that as soon as we start writing to it we can no longer read anything from it.

[This StackOverflow answer](https://stackoverflow.com/a/59467131/12397979) suggests to me that the current strategy of opening the file twice should work in theory. Right now I can't see what the significant difference is between that answer and our code.

I think

**Comment by mpkorstanje** [comment]
> It appears to me that the input stream is not independent from the output stream, so that as soon as we start writing to it we can no longer read anything from it.

It's a file so that is to be expected.

We'd have to read the entire input before writing the output if we want to process the file in place.
